export const gameCores: { [key: string]: string } = {
    "Atari 2600": "atari2600",
    "Atari 5200": "atari5200",
    "Atari 7800": "atari7800",
    "Atari Jaguar": "jaguar",
    "Atari Lynx": "lynx",
    "Nintendo Entertainment System": "nes",
    "Nintendo 64": "n64",
    "Nintendo Game Boy Advance": "gba",
    "Nintendo Game Boy": "gb",
    "Nintendo DS": "nds",
    "Super Nintendo Entertainment System": "snes",
    "Sega Master System": "segaMS",
    "Sega Mega Drive": "segaMD",
    "Virtual Boy": "vb"
};

export const gameMappings: { [key: string]: { url: string, core: string } } = {
    'digdug': { url: "/rom/atari-2600/DigDug.a52", core: gameCores["Atari 2600"] },
    'et': { url: "/rom/atari-2600/ET.a26", core: gameCores["Atari 2600"] },
    'fatalrun': { url: "/rom/atari-2600/FatalRun.a26", core: gameCores["Atari 2600"] },
    'gravitar': { url: "/rom/atari-2600/Gravitar.a26", core: gameCores["Atari 2600"] },
    'phoenix': { url: "/rom/atari-2600/Phoenix.a26", core: gameCores["Atari 2600"] },

    'choplifter': { url: "/rom/atari-5200/Choplifter.a52", core: gameCores["Atari 5200"] },
    'joust': { url: "/rom/atari-5200/Joust.a52", core: gameCores["Atari 5200"] },
    'missilecommand': { url: "/rom/atari-5200/MissileCommand.a52", core: gameCores["Atari 5200"] },
    'moonpatrol': { url: "/rom/atari-5200/MoonPatrol.a52", core: gameCores["Atari 5200"] },
    'realsportstennis': { url: "/rom/atari-5200/RealsportsTennis.a52", core: gameCores["Atari 5200"] },

    'asteroids': { url: "/rom/atari-7800/Asteroids.a78", core: gameCores["Atari 7800"] },
    'mspacman': { url: "/rom/atari-7800/MsPac-Man.a78", core: gameCores["Atari 7800"] },
    'poleposition2': { url: "/rom/atari-7800/PolePosition2.a78", core: gameCores["Atari 7800"] },
    'summergames': { url: "/rom/atari-7800/SummerGames.a78", core: gameCores["Atari 7800"] },
    'wintergames': { url: "/rom/atari-7800/WinterGames.a78", core: gameCores["Atari 7800"] },

    'atarikarts': { url: "/rom/atari-jaguar/AtariKarts.j64", core: gameCores["Atari Jaguar"] },
    'doom': { url: "/rom/atari-jaguar/Doom.j64", core: gameCores["Atari Jaguar"] },
    'doubledragon': { url: "/rom/atari-jaguar/DoubleDragon.j64", core: gameCores["Atari Jaguar"] },
    'nbajam': { url: "/rom/atari-jaguar/NBAJam.j64", core: gameCores["Atari Jaguar"] },
    'rayman': { url: "/rom/atari-jaguar/Rayman.j64", core: gameCores["Atari Jaguar"] },

    'batmanreturns': { url: "/rom/atari-lynx/BatmanReturns.lnx", core: gameCores["Atari Lynx"] },
    'harddrivin': { url: "/rom/atari-lynx/HardDrivin.lnx", core: gameCores["Atari Lynx"] },
    'ninjagaiden': { url: "/rom/atari-lynx/NinjaGaiden.lnx", core: gameCores["Atari Lynx"] },
    'pacland': { url: "/rom/atari-lynx/Pacland.lnx", core: gameCores["Atari Lynx"] },
    'roadblasters': { url: "/rom/atari-lynx/RoadBlasters.lnx", core: gameCores["Atari Lynx"] },

    'donkeykong': { url: "/rom/gameboy/DonkeyKong.gb", core: gameCores["Nintendo Game Boy"] },
    'kirbypartyland': { url: "/rom/gameboy/KirbyPinballLand.gb", core: gameCores["Nintendo Game Boy"] },
    'megamanv': { url: "/rom/gameboy/MegamanV.gb", core: gameCores["Nintendo Game Boy"] },
    'wariolandsupermarioland3': { url: "/rom/gameboy/SuperMarioLand3.gb", core: gameCores["Nintendo Game Boy"] },
    'tetris': { url: "/rom/gameboy/Tetris.gb", core: gameCores["Nintendo Game Boy"] },

    'sonicadvance': { url: "/rom/gameboy-advance/SonicAdvance.gba", core: gameCores["Nintendo Game Boy Advance"] },
    'sonicadvance2': { url: "/rom/gameboy-advance/SonicAdvance2.gba", core: gameCores["Nintendo Game Boy Advance"] },
    'sonicadvance3': { url: "/rom/gameboy-advance/SonicAdvance3.gba", core: gameCores["Nintendo Game Boy Advance"] },
    'sonicbattle': { url: "/rom/gameboy-advance/SonicBattle.gba", core: gameCores["Nintendo Game Boy Advance"] },
    'sonicpinballparty': { url: "/rom/gameboy-advance/SonicPinballParty.gba", core: gameCores["Nintendo Game Boy Advance"] },

    'adventuresoflolo': { url: "/rom/nes/AdventuresofLolo.nes", core: gameCores["Nintendo Entertainment System"] },
    'duckhunt': { url: "/rom/nes/DuckHunt.nes", core: gameCores["Nintendo Entertainment System"] },
    'gyromite': { url: "/rom/nes/Gyromite.nes", core: gameCores["Nintendo Entertainment System"] },
    'jackal': { url: "/rom/nes/Jackal.nes", core: gameCores["Nintendo Entertainment System"] },
    'supermariobros': { url: "/rom/nes/SuperMarioBros.nes", core: gameCores["Nintendo Entertainment System"] },

    'legendofzeldatheocarinaoftime': { url: "/rom/nintendo-64/LegendofZeldaTheOcarinaofTime.n64", core: gameCores["Nintendo 64"] },
    'mariokart64': { url: "/rom/nintendo-64/MarioKart64.n64", core: gameCores["Nintendo 64"] },
    'pokemonstadium': { url: "/rom/nintendo-64/PokemonStadium.n64", core: gameCores["Nintendo 64"] },
    'supermario64': { url: "/rom/nintendo-64/SuperMario64.n64", core: gameCores["Nintendo 64"] },
    'supersmashbros': { url: "/rom/nintendo-64/SuperSmashBros.n64", core: gameCores["Nintendo 64"] },

    'animalcrossingwildworld': { url: "/rom/nintendo-ds/AnimalCrossingWildWorld.nds", core: gameCores["Nintendo DS"] },
    'ghostbusters': { url: "/rom/nintendo-ds/Ghostbusters.nds", core: gameCores["Nintendo DS"] },
    'kirbycanvascurse': { url: "/rom/nintendo-ds/KirbyCanvasCurse.nds", core: gameCores["Nintendo DS"] },
    'mariokartds': { url: "/rom/nintendo-ds/MarioKartDS.nds", core: gameCores["Nintendo DS"] },
    'sonicrush': { url: "/rom/nintendo-ds/SonicRush.nds", core: gameCores["Nintendo DS"] },

    'alexkiddinmiracleworld': { url: "/rom/sega-master-system/AlexKiddinMiracleWorld.sms", core: gameCores["Sega Master System"] },
    'goldenaxe': { url: "/rom/sega-master-system/GoldenAxe.sms", core: gameCores["Sega Master System"] },
    'sonicblast': { url: "/rom/sega-master-system/SonicBlast.sms", core: gameCores["Sega Master System"] },
    'sonichaos': { url: "/rom/sega-master-system/SonicChaos.sms", core: gameCores["Sega Master System"] },
    'sonicspinball': { url: "/rom/sega-master-system/SonicSpinball.sms", core: gameCores["Sega Master System"] },

    'sonic1': { url: "/rom/sega-mega-drive/SonicTheHedgehog.md", core: gameCores["Sega Mega Drive"] },
    'sonic2': { url: "/rom/sega-mega-drive/SonicTheHedgehog2.md", core: gameCores["Sega Mega Drive"] },
    'sonic3': { url: "/rom/sega-mega-drive/SonicTheHedgehog3.md", core: gameCores["Sega Mega Drive"] },
    'sonic3knuckles': { url: "/rom/sega-mega-drive/Sonic3Knuckles.md", core: gameCores["Sega Mega Drive"] },
    'sonic3dblast': { url: "/rom/sega-mega-drive/Sonic3DBlast.gen", core: gameCores["Sega Mega Drive"] },

    'donkeykongcountry': { url: "/rom/snes/DonkeyKongCountry.smc", core: gameCores["Super Nintendo Entertainment System"] },
    'streetfighter2turbo': { url: "/rom/snes/StreetFighterIITurbo.smc", core: gameCores["Super Nintendo Entertainment System"] },
    'supermariokart': { url: "/rom/snes/SuperMarioKart.sfc", core: gameCores["Super Nintendo Entertainment System"] },
    'supermarioworld': { url: "/rom/snes/SuperMarioWorld.sfc", core: gameCores["Super Nintendo Entertainment System"] },
    'supermarioworld2': { url: "/rom/snes/SuperMarioWorld2.sfc", core: gameCores["Super Nintendo Entertainment System"] },

    'jackbros': { url: "/rom/virtualboy/JackBros.vb", core: gameCores["Virtual Boy"] },
    'marioclash': { url: "/rom/virtualboy/MarioClash.vb", core: gameCores["Virtual Boy"] },
    'nesterfunkybowling': { url: "/rom/virtualboy/NesterFunkyBowling.vb", core: gameCores["Virtual Boy"] },
    'redalarm': { url: "/rom/virtualboy/RedAlarm.vb", core: gameCores["Virtual Boy"] },
    'teleroboxer': { url: "/rom/virtualboy/Teleroboxer.vb", core: gameCores["Virtual Boy"] },
};

export const gameDetails: { [key: string]: { title: string, publisher: string } } = {
    'digdug': { title: 'Dig Dug', publisher: 'ATARI' },
    'et': { title: 'E.T. the Extra-Terrestrial', publisher: 'ATARI' },
    'fatalrun': { title: 'Fatal Run', publisher: 'ATARI' },
    'gravitar': { title: 'Gravitar', publisher: 'ATARI' },
    'phoenix': { title: 'Phoenix', publisher: 'ATARI' },

    'choplifter': { title: 'Choplifter', publisher: 'ATARI' },
    'joust': { title: 'Joust', publisher: 'ATARI' },
    'missilecommand': { title: 'Missile Command', publisher: 'ATARI' },
    'moonpatrol': { title: 'Moon Patrol', publisher: 'ATARI' },
    'realsportstennis': { title: 'RealSports Tennis', publisher: 'ATARI' },

    'asteroids': { title: 'Asteroids', publisher: 'ATARI' },
    'mspacman': { title: 'Ms. Pacman', publisher: 'NAMCO' },
    'poleposition2': { title: 'Pole Position 2', publisher: 'NAMCO' },
    'summergames': { title: 'Summer Games', publisher: 'EPYX' },
    'wintergames': { title: 'Winter Games', publisher: 'EPYX' },

    'atarikarts': { title: 'Atari Karts', publisher: 'MIRACLE DESIGNS' },
    'doom': { title: 'DOOM', publisher: 'ID SOFTWARE' },
    'doubledragon': { title: 'Double Dragon V: The Shadow Falls', publisher: 'LELAND INTERACTIVE MEDIA' },
    'nbajam': { title: 'NBA Jam', publisher: 'ACCLAIM ENTERTAINMENT' },
    'rayman': { title: 'Rayman', publisher: 'UBISOFT' },

    'batmanreturns': { title: 'Batman Returns', publisher: 'KONAMI' },
    'harddrivin': { title: 'Hard Drivin', publisher: 'ATARI' },
    'ninjagaiden': { title: 'Ninja Gaiden', publisher: 'NATSUME' },
    'pacland': { title: 'Pac-Land', publisher: 'NAMCO' },
    'roadblasters': { title: 'Road Blasters', publisher: 'ATARI' },

    'donkeykong': { title: 'Donkey Kong', publisher: 'NINTENDO' },
    'kirbypartyland': { title: 'Kirby Pinball Land', publisher: 'NINTENDO' },
    'megaman': { title: 'Mega Man V', publisher: 'CAPCOM' },
    'tetris': { title: 'Tetris', publisher: 'BLUE BOX' },
    'wariolandsupermarioland3': { title: 'Wario Land: Super Mario Land 3', publisher: 'NINTENDO' },

    'sonicadvance': { title: 'Sonic Advance', publisher: 'SEGA' },
    'sonicadvance2': { title: 'Sonic Advance 2', publisher: 'SEGA' },
    'sonicadvance3': { title: 'Sonic Advance 3', publisher: 'SEGA' },
    'sonicbattle': { title: 'Sonic Battle', publisher: 'SEGA' },
    'sonicpinballparty': { title: 'Sonic Pinball Party', publisher: 'SEGA' },

    'mariokart': { title: 'Mario Kart 64', publisher: 'NINTENDO' },
    'pokemonstadium': { title: 'Pokemon Stadium', publisher: 'NINTENDO' },
    'supermario64': { title: 'Super Mario 64', publisher: 'NINTENDO' },
    'supersmashbros': { title: 'Super Smash Bros.', publisher: 'NINTENDO' },
    'zeldaocarinaoftime': { title: 'The Legend Of Zelda Ocarina Of Time', publisher: 'NINTENDO' },

    'animalcrossing': { title: 'Animal Crossing: Wild World', publisher: 'NINTENDO' },
    'ghost': { title: 'Ghostbusters: The Video Game', publisher: 'RED FLY STUDIO' },
    'kirby': { title: 'Kirby Canvas Curse', publisher: 'HAL LABORATORY' },
    'mariokartds': { title: 'Mario Kart DS', publisher: 'NINTENDO' },
    'sonicrush': { title: 'Sonic Rush', publisher: 'SEGA' },

    'adventureoflolo': { title: 'Adventure of Lolo', publisher: 'HAL LABORATORY' },
    'duckhunt': { title: 'Duck Hunt', publisher: 'NINTENDO' },
    'gyromite': { title: 'Gyromite', publisher: 'NINTENDO' },
    'jackal': { title: 'Jackal', publisher: 'KONAMI' },
    'supermariobros': { title: 'Super Mario Bros.', publisher: 'NINTENDO' },

    'sonic1': { title: 'Sonic The Hedgehog', publisher: 'SEGA' },
    'sonic2': { title: 'Sonic The Hedgehog 2', publisher: 'SEGA' },
    'sonic3': { title: 'Sonic The Hedgehog 3', publisher: 'SEGA' },
    'sonic3knuckles': { title: 'Sonic The Hedgehog 3 & Knuckles', publisher: 'SEGA' },
    'sonic3dblast': { title: 'Sonic 3D Blast', publisher: 'SEGA' },

    'alexkiddinmiracleworld': { title: 'Alex Kidd in Miracle World', publisher: 'SEGA' },
    'goldenaxe': { title: 'Golden Axe', publisher: 'SEGA' },
    'sonicblast': { title: 'Sonic Blast', publisher: 'ANCIENT' },
    'sonicchaos': { title: 'Sonic Chaos', publisher: 'ANCIENT' },
    'sonicspinball': { title: 'Sonic Spinball', publisher: 'SEGA' },

    'donkeykongcountry': { title: 'Donkey Kong Country', publisher: 'RARE' },
    'streetfighter2turbo': { title: 'Street Fighter 2 Turbo', publisher: 'CAPCOM' },
    'supermariokart': { title: 'Super Mario Kart', publisher: 'NINTENDO' },
    'supermarioworld': { title: 'Super Mario World', publisher: 'NINTENDO' },
    'supermarioworld2yoshiisland': { title: 'Super Mario World 2: Yoshi Island', publisher: 'NINTENDO' },

    'jack': { title: 'Jack Bros', publisher: 'ATLUS' },
    'marioclash': { title: 'Mario Clash', publisher: 'NINTENDO' },
    'nestersfunkybowling': { title: 'Nesters Funky Bowling', publisher: 'NINTENDO' },
    'redalarm': { title: 'Red Alarm', publisher: 'T&E SOFT' },
    'teleroboxer': { title: 'Telero Boxer', publisher: 'KONAMI' },
};
